import Foundation
import Ignite

struct PrivacyPolicy: StaticPage {
    var title = "Privacy Policy"
    var path = "/privacypolicy"

    var body: some HTML {
        Section {
            Text("Privacy Policy")
                .font(.title1)
                .foregroundStyle("#00ffff")
                .margin(.top, 30)

            Text("english")
                .font(.title3)
                .foregroundStyle(.light)
                .margin(.top, 30)

            Text("This Privacy Policy describes if and how the App 'HandsfreeLaptimer - FPV + RC' uses, collects, discloses and protects information generated by its use. By downloading and using the app, you agree to the practices described herein.")
                .foregroundStyle(.light)

            Text("Privacy Policy")
                .font(.title2)
                .foregroundStyle("#00ffff")
                .margin(.top, 30)

            Emphasis("last updated: Nov 22nd, 2025")
                .foregroundStyle("#666666")

            Text("The app 'HandsfreeLaptimer - FPV + RC' doesn't collect, store, transmit or sell your data, except for data and analytics that Apple provides for developers you decided to share in iOS Settings. The app uses speech recognition to handle spoken commands. Recognised speech will be processed on device, not saved persistently or personalised. It is not shared with the developer or anybody else and won't leave the device.")
                .foregroundStyle(.light)
                .margin(.top, 20)

            Text("If you contact me by email, your address will never be shared and only used to answer you.")
                .foregroundStyle(.light)
                .margin(.top, 20)

            Text("Changes to this Privacy Policy")
                .font(.title3)
                .foregroundStyle("#00ffff")
                .margin(.top, 30)

            Text("This policy may be updated to reflect changes in technology, legal requirements or data-handling practices. Changes will be listed in section \"last updated\" on top of this page.")
                .foregroundStyle(.light)

            Text("Contact")
                .font(.title3)
                .foregroundStyle("#00ffff")
                .margin(.top, 30)

            Text("If you have any questions about this Privacy Policy, you can contact me by email: handsfreelaptimer(at)gmail.com")
                .foregroundStyle(.light)

            Divider()
                .margin(.vertical, 40)

            Text("deutsch")
                .font(.title3)
                .foregroundStyle(.light)

            Text("Diese Datenschutz-Richtlinie beschreibt ob und wie die App \"HandsfreeLaptimer - FPV + RC\" Informationen nutzt, sammelt, veröffentlicht oder schützt, die bei ihrer Nutzung entstehen. Durch das Herunterladen und Nutzen dieser App erklärt sich die Nutzer:in mit den hier geschilderten Praktiken einverstanden.")
                .foregroundStyle(.light)
                .margin(.top, 20)

            Text("Datenschutz-Richtlinie")
                .font(.title2)
                .foregroundStyle("#00ffff")
                .margin(.top, 30)

            Emphasis("zuletzt aktualisiert am: 22. Nov 2025")
                .foregroundStyle("#666666")

            Text("Die App \"HandsfreeLaptimer - FPV + RC\" sammelt, speichert und übermittelt keinerlei Benutzer-Daten. Die App nutzt ein Spracherkennungsmodul, um Sprachbefehle zu erfassen. Erkannte Sprache wird ausschließlich auf dem Gerät verarbeitet, wird nicht persistent oder personalisiert gespeichert und verlässt nie das Gerät. Durch die Nutzung dieser App können von Apple Analyse-Daten für Entwickler erhoben werden, sofern dem in den iOS-Systemeinstellungen zugestimmt wurde.")
                .foregroundStyle(.light)
                .margin(.top, 20)

            Text("Kontakt: handsfreelaptimer(at)gmail.com")
                .foregroundStyle(.light)
                .margin(.top, 20)
        }
        .background("#000000")
        .padding(.top, 100)
        .padding(.bottom, 60)
        .padding(.horizontal, 40)
    }
}
